import { Card, CardActionArea, CardMedia, CardContent, Typography, Grid, IconButton, Menu, MenuItem } from '@mui/material';
import type { NextPage } from 'next'
import Head from 'next/head'
import * as React from 'react';
import EmployeItem from '../../../src/components/Employee/EmployeeItem';
import MainLayout from '../../../src/layout/layout';
import { NextPageWithLayout } from '../../_app';

const users = [
  {
    "id": 4,
    "name": "Roman",
    "liked": 2712,
    "description": "Architect",
    "avatar": "/uploads/1.jpeg",
    "job_id": 1,
    "location_id": 1
  },
  {
    "id": 6,
    "name": "Petya",
    "liked": 284,
    "description": "Backend developer",
    "avatar": "/uploads/3.png",
    "job_id": 3,
    "location_id": 3
  },
  {
    "id": 1,
    "name": "Nikita",
    "liked": 161,
    "description": "Frontend developer",
    "avatar": "/uploads/1.jpeg",
    "job_id": 2,
    "location_id": 1
  },
  {
    "id": 2,
    "name": "Danila",
    "liked": 1149,
    "description": "Backend developer",
    "avatar": "/uploads/2.png",
    "job_id": 3,
    "location_id": 2
  },
  {
    "id": 3,
    "name": "Omar",
    "liked": 5280,
    "description": "Architect",
    "avatar": "/uploads/3.png",
    "job_id": 1,
    "location_id": 2
  },
  {
    "id": 5,
    "name": "Vasya",
    "liked": 2713,
    "description": "Frontend developer",
    "avatar": "/uploads/2.png",
    "job_id": 2,
    "location_id": 3
  }
];

const Employe: NextPageWithLayout = ({ children }: any) => {
  return (
    <div className='emp'>
      <Head>
        <title>Emp page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid container spacing={2} columns={12}>
        {[...users, ...users, ...users, ...users, ...users, ...users].map((user, key) => {
          return <EmployeItem key={key} user={user} />
        })}
      </Grid>
    </div>
  )
}

Employe.getLayout = function getLayout(page: any) {
  return (
    <MainLayout className="layout-2">
      {page}
    </MainLayout>
  )
}

export default Employe
