import Head from 'next/head'
import * as React from 'react';
import ScreenLogo from '../src/components/ScreenLogo/ScreenLogo';
import WelcomeScreen from '../src/components/Welcome';
import { NextPageWithLayout } from './_app';

const Employees: NextPageWithLayout = ({ children }: any) => {
  return (
    <div className='employee-page'>
      <Head>
        <title>Emp page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      employees
    </div>
  )
}

export default Employees
